<?php

namespace Database\Seeders;

use App\Models\MeasureUnit;
use Illuminate\Database\Seeder;

class MeasureUnitSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $units = [
            ['code' => 'KGM', 'name' => 'KILOGRAMOS', 'symbol' => 'Kg'],
            ['code' => 'LBR', 'name' => 'LIBRAS', 'symbol' => 'Lb'],
            ['code' => 'LTN', 'name' => 'TONELADAS LARGAS', 'symbol' => 'Tl'],
            ['code' => 'TNE', 'name' => 'TONELADAS', 'symbol' => 'Tm'],
            ['code' => 'STN', 'name' => 'TONELADAS CORTAS', 'symbol' => 'Tc'],
            ['code' => 'GRM', 'name' => 'GRAMOS', 'symbol' => 'g'],
            ['code' => 'NIU', 'name' => 'UNIDADES', 'symbol' => 'Und.'],
            ['code' => 'LTR', 'name' => 'LITROS', 'symbol' => 'L'],
            ['code' => 'NIU', 'name' => 'GALONES', 'symbol' => 'Galon'],
            ['code' => 'BLL', 'name' => 'BARRILES', 'symbol' => 'Barril'],
            ['code' => 'CA', 'name' => 'LATAS', 'symbol' => 'lata'],
            ['code' => 'BX', 'name' => 'CAJAS', 'symbol' => 'caja'],
            ['code' => 'MIL', 'name' => 'MILLARES', 'symbol' => 'm'],
            ['code' => 'NIU', 'name' => 'METROS CUBICOS', 'symbol' => 'm3'],
            ['code' => 'MTR', 'name' => 'METRO LINEAL', 'symbol' => 'm.'],
            ['code' => 'DZN', 'name' => 'DOCENA', 'symbol' => 'doc'],
            ['code' => 'CEN', 'name' => 'CIENTO', 'symbol' => 'Ciento'],
            ['code' => 'PK', 'name' => 'PAQUETE', 'symbol' => 'Pqt'],
            ['code' => 'NIU', 'name' => 'JABAS', 'symbol' => 'jaba'],
            ['code' => 'ZZ', 'name' => 'SERVICIO', 'symbol' => 'servicio'],
            ['code' => 'NIU', 'name' => 'MEDIA DOCENA', 'symbol' => 'med.doc.'],
            ['code' => 'BE', 'name' => 'FARDO', 'symbol' => 'Fdo'],
            ['code' => 'NIU', 'name' => 'MEDIA CAJA', 'symbol' => 'Med.Caj.'],
            ['code' => 'BG', 'name' => 'BOLSA', 'symbol' => 'Bolsa'],
            ['code' => 'NIU', 'name' => 'CAJETILLA', 'symbol' => 'Cajt.'],
            ['code' => 'NIU', 'name' => 'PACK', 'symbol' => 'Pack'],
            ['code' => 'NIU', 'name' => 'DISPLEY', 'symbol' => 'Displey'],
            ['code' => 'NIU', 'name' => 'TIRA', 'symbol' => 'Tira'],
            ['code' => 'NIU', 'name' => 'SIXPAK', 'symbol' => 'Sixpak'],
            ['code' => 'NIU', 'name' => 'TAPER', 'symbol' => 'Taper'],
            ['code' => 'NIU', 'name' => 'FRASCO', 'symbol' => 'Fr'],
            ['code' => 'NIU', 'name' => 'VASO', 'symbol' => 'Vaso'],
            ['code' => 'NIU', 'name' => 'DISPENSADOR', 'symbol' => 'Dispens.'],
            ['code' => 'NIU', 'name' => 'BANDEJA', 'symbol' => 'Bandeja'],
            ['code' => 'NIU', 'name' => 'PLATO', 'symbol' => 'Plato'],
            ['code' => 'NIU', 'name' => 'POMO', 'symbol' => 'Pomo'],
            ['code' => 'NIU', 'name' => 'SACHET', 'symbol' => 'Sachet'],
            ['code' => 'NIU', 'name' => 'MEDIO DISPLEY', 'symbol' => 'M.Displey'],
            ['code' => 'BJ', 'name' => 'BALDE', 'symbol' => 'Bal.'],
            ['code' => 'NIU', 'name' => 'SACO', 'symbol' => 'Saco'],
            ['code' => 'NIU', 'name' => 'PAR', 'symbol' => 'Par'],
            ['code' => 'NIU', 'name' => 'POTE', 'symbol' => 'Pote'],
            ['code' => 'NIU', 'name' => 'ROLLO', 'symbol' => 'Rollo'],
            ['code' => 'NIU', 'name' => 'PLANCHA', 'symbol' => 'Plancha'],
            ['code' => 'NIU', 'name' => 'PIEZA', 'symbol' => 'Pieza'],
            ['code' => 'BO', 'name' => 'BOTELLAS', 'symbol' => 'BO'],
            ['code' => 'NIU', 'name' => 'METROS CUADRADOS', 'symbol' => 'm2'],
            ['code' => 'NIU', 'name' => 'VARILLA', 'symbol' => 'varilla'],
            ['code' => 'FOT', 'name' => 'PIES', 'symbol' => 'Ft'],
            ['code' => 'SET', 'name' => 'JUEGOS', 'symbol' => 'Juego'],
            ['code' => 'NIU', 'name' => 'CAJON', 'symbol' => 'Cajon'],
            ['code' => 'NIU', 'name' => 'GRUESA', 'symbol' => 'Gruesa'],
            ['code' => 'NIU', 'name' => 'MEDIA GRUESA', 'symbol' => 'Media Grue'],
            ['code' => 'NIU', 'name' => 'MEDIO CIENTO', 'symbol' => 'Medio Cien'],
            ['code' => 'NIU', 'name' => 'MEDIO MILLAR', 'symbol' => 'Medio Mill'],
            ['code' => 'NIU', 'name' => 'ESTUCHE', 'symbol' => 'Estuche'],
            ['code' => 'NIU', 'name' => 'PIE CUADRADO', 'symbol' => 'Ft2'],
            ['code' => 'ST', 'name' => 'PLIEGO', 'symbol' => 'Pliego'],
            ['code' => 'RM', 'name' => 'RESMA', 'symbol' => 'Resma'],
            ['code' => 'NIU', 'name' => 'TONELADA', 'symbol' => 'Tonelada'],
            ['code' => 'KGM', 'name' => 'KILOGRAMOSS', 'symbol' => 'Kg'],
            ['code' => 'NIU', 'name' => 'CAPSULA', 'symbol' => 'Cap.'],
            ['code' => 'NIU', 'name' => 'TABLETA', 'symbol' => 'Tabl.'],
            ['code' => 'NIU', 'name' => 'SET', 'symbol' => 'Set'],
            ['code' => 'NIU', 'name' => 'BLISTER', 'symbol' => 'Blister'],
            ['code' => 'ONZ', 'name' => 'ONZAS', 'symbol' => 'Onzas'],
            ['code' => 'MLT', 'name' => 'MILILITRO', 'symbol' => 'ml'],
            ['code' => 'NIU', 'name' => 'DOSIS', 'symbol' => 'dosis'],
            ['code' => 'NIU', 'name' => 'MEDIO SACO', 'symbol' => 'Med.Saco'],
            ['code' => 'NIU', 'name' => 'MEDIA BOLSA', 'symbol' => 'Med.Bolsa'],
            ['code' => 'NIU', 'name' => 'MEDIO PAQUETE', 'symbol' => 'Med.Paq.'],
            ['code' => 'CMT', 'name' => 'CENTIMETRO LINEAL', 'symbol' => 'cm.'],
            ['code' => 'CMK', 'name' => 'CENTIMETRO CUADRADO', 'symbol' => 'cm2.'],
            ['code' => '4A', 'name' => 'BOBINAS', 'symbol' => 'Bobina'],
            ['code' => 'CT', 'name' => 'CARTONES', 'symbol' => 'carton'],
            ['code' => 'CMQ', 'name' => 'CENTIMETRO CUBICO', 'symbol' => 'Cm3'],
            ['code' => 'CY', 'name' => 'CILINDRO', 'symbol' => 'Cilindro'],
            ['code' => 'CJ', 'name' => 'CONOS', 'symbol' => 'cono'],
            ['code' => 'DZP', 'name' => 'DOCENA POR 10**6', 'symbol' => 'docena'],
            ['code' => 'GLI', 'name' => 'GALON INGLES (4,545956L)', 'symbol' => 'GalonI'],
            ['code' => 'GRO', 'name' => 'GRUESA', 'symbol' => 'gruesa'],
            ['code' => 'HLT', 'name' => 'HECTOLITRO', 'symbol' => 'Hectolitro'],
            ['code' => 'LEF', 'name' => 'HOJA', 'symbol' => 'hoja'],
            ['code' => 'KTM', 'name' => 'KILOMETRO', 'symbol' => 'km'],
            ['code' => 'KWH', 'name' => 'KILOVATIO HORA', 'symbol' => 'kwh'],
            ['code' => 'KT', 'name' => 'KIT', 'symbol' => 'kit'],
            ['code' => 'MWH', 'name' => 'MEGAWATT HORA', 'symbol' => 'mwh'],
            ['code' => 'NIU', 'name' => 'METRO CUADRADO', 'symbol' => 'mtk'],
            ['code' => 'MTQ', 'name' => 'METRO CUBICO', 'symbol' => 'm3'],
            ['code' => 'MGM', 'name' => 'MILIGRAMOS', 'symbol' => 'miligramo'],
            ['code' => 'MMT', 'name' => 'MILIMETRO', 'symbol' => 'milimetro'],
            ['code' => 'MMK', 'name' => 'MILIMETRO CUADRADO', 'symbol' => 'milimetro2'],
            ['code' => 'MMQ', 'name' => 'MILIMETRO CUBICO', 'symbol' => 'milimetro3'],
            ['code' => 'UM', 'name' => 'MILLON DE UNIDADES', 'symbol' => 'millon'],
            ['code' => 'PF', 'name' => 'PALETAS', 'symbol' => 'paleta'],
            ['code' => 'PR', 'name' => 'PAR', 'symbol' => 'par'],
            ['code' => 'FTK', 'name' => 'PIES CUADRADOS', 'symbol' => 'pie2'],
            ['code' => 'FTQ', 'name' => 'PIES CUBICOS', 'symbol' => 'pie3'],
            ['code' => 'C62', 'name' => 'PIEZAS', 'symbol' => 'pieza'],
            ['code' => 'PG', 'name' => 'PLACAS', 'symbol' => 'placa'],
            ['code' => 'INH', 'name' => 'PULGADAS', 'symbol' => 'pulgada'],
            ['code' => 'DR', 'name' => 'TAMBOR', 'symbol' => 'tambor'],
            ['code' => 'STN', 'name' => 'TONELADA CORTA', 'symbol' => 'tonelada'],
            ['code' => 'LTN', 'name' => 'TONELADA LARGA', 'symbol' => 'toneladala'],
            ['code' => 'TU', 'name' => 'TUBOS', 'symbol' => 'tubo'],
            ['code' => 'YRD', 'name' => 'YARDA', 'symbol' => 'yarda'],
            ['code' => 'YDK', 'name' => 'YARDA CUADRADA', 'symbol' => 'yarda2'],
            ['code' => 'AMP', 'name' => 'AMPOLLAS', 'symbol' => 'ampo'],
            ['code' => 'SOB', 'name' => 'SOBRE', 'symbol' => 'sobre'],
            ['code' => 'SPY', 'name' => 'SPRAY', 'symbol' => 'spray'],
            ['code' => 'BOX', 'name' => 'BOX', 'symbol' => 'box'],
        ];

        foreach ($units as $unit) {
            MeasureUnit::create($unit);
        }
    }
}
